# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `main` gem.
# Please instead update this file by running `bin/tapioca gem main`.

# typed: true

# THIS IS AN EMPTY RBI FILE.
# see https://github.com/Shopify/tapioca/wiki/Manual-Gem-Requires
