# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `sexp_processor` gem.
# Please instead update this file by running `bin/tapioca gem sexp_processor`.

# typed: true

# THIS IS AN EMPTY RBI FILE.
# see https://github.com/Shopify/tapioca/wiki/Manual-Gem-Requires
