# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `sorted_set` gem.
# Please instead update this file by running `bin/tapioca gem sorted_set`.

# typed: true

class SortedSet < ::Set
  def initialize(*args); end
end
