# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `titleize` gem.
# Please instead update this file by running `bin/tapioca gem titleize`.

# typed: true

class String
  include ::Comparable
  include ::Colorize::InstanceMethods
  include ::JSON::Ext::Generator::GeneratorMethods::String
  extend ::Colorize::ClassMethods
  extend ::JSON::Ext::Generator::GeneratorMethods::String::Extend

  def titlecase(opts = T.unsafe(nil)); end
  def titlecase!; end
  def titleize(opts = T.unsafe(nil)); end
  def titleize!; end
end

module Titleize
  extend ::Titleize

  def phrases(title); end
  def titleize(title); end

  private

  def ends_with_punctuation?(word); end
  def small_word?(word); end
end

Titleize::SMALL_WORDS = T.let(T.unsafe(nil), Array)
