# frozen_string_literal: true

source "https://rubygems.org"

gemspec

# Autogenerated Rake Tasks
gem "rake", "~> 13.0"

# Ruby unit tests
gem "rspec", "~> 3.0"

# Code checker
gem "rubocop", "~> 1.7"

# Code checker for rake
gem "rubocop-rake", "~> 0.6.0"

# Code checker for rspec
gem "rubocop-rspec", "~> 2.5"

# Audit bundled gems
gem "bundler-audit", "~> 0.9.0"

# Markdown linter
gem "mdl", "~> 0.11.0"

# Code quality check
gem "reek", "~> 6.0"

# Code churn check
gem "churn", "~> 1.0"

# Code metrics
gem "code_metrics", "~> 0.1.3"
