# frozen_string_literal: true

source "https://rubygems.org"

gemspec

# Autogenerated Rake Tasks
gem "rake", "~> 13.0"

# Ruby unit tests
gem "rspec", "~> 3.0", group: :test

# Code checker
gem "rubocop", "~> 1.7"

# Code checker for rake
gem "rubocop-rake", "~> 0.6.0"

# Code checker for rspec
gem "rubocop-rspec", "~> 2.5"

# Audit bundled gems
gem "bundler-audit", "~> 0.9.0"

# Markdown linter
gem "mdl", "~> 0.11.0"

# Code quality check
gem "reek", "~> 6.0"

# Code churn check
gem "churn", "~> 1.0"

# Code metrics
gem "code_metrics", "~> 0.1.3"

# Code Coverage
gem "simplecov", "~> 0.21.2", require: false, group: :test

# Codecov reporter
gem "codecov", "~> 0.6.0", require: false, group: :test

# Generate rspec skeleton

# Debugging tool (required by rspec-scaffold)
gem "pry", "~> 0.14.1"

# gem version management
gem "gem-release", "~> 2.2"

# Documentation Coverage Tool
gem "inch", "~> 0.8.0"

# Documentation Generation Tool
gem "yard", "~> 0.9.26"

# Required by yard
gem "rack", "~> 2.2"

# Required by yard
gem "webrick", "~> 1.7"

# Ruby Typing
gem "rbs", "~> 1.6"

# Ruby Typing Profiler
gem "typeprof", "~> 0.20.0"

# Ruby Typing based on yard comments
gem "sord", "~> 3.0.0"

# Required by sord
gem "sorted_set", "~> 1.0"

# Ruby Type Checker
gem "sorbet", "~> 0.5.9238", group: :development

# Ruby Type Checker Runtime
gem "sorbet-runtime", "~> 0.5.9238"

# Ruby Type Checker File Generation
gem "tapioca", "~> 0.5.2", require: false, group: :development
